# Feel free to translate this to your native language
[flux]
 energystat = "Energy: %s / %s F"
 gen = "Generating %s F/t"
 usage = "Using %s F/t"
 update = "Flux has a newer version: %s"
 works_underwater = "It even works underwater!"

[flux.gift]
 invalid = "Invalid Gift!"

[flux.gift.text]
 newyear = "Happy New Year!"
 valentine = "It's Valentine's Day! Hearts for You!"
 pi = "Happy Pi Day!"
 water = "It's Water Day!"

[flux.chip]
 speed = "Speed"
 energy = "Energy"

[flux.configgui]
 fluxGenBaseEnergyValue = "Base energy generation for Flux Generator"
 basicMachineEU = "Energy usage for basic machines (Grinding Mill, Washer, etc.)"

[item.flux]
 mftool = "Flux Tool"
 gift = "Flux Gift"
 machine_base = "Machine Base"
 chip = "Flux Chip"
 seal = "Flux Seal"
 glue = "Flux Glue"
 paste = "Flux Paste"
 iron_grit = "Iron Grit"
 gold_grit = "Gold Grit"
 copper_grit = "Copper Grit"
 tin_grit = "Tin Grit"
 iron_dust = "Iron Dust"
 gold_dust = "Gold Dust"
 copper_dust = "Copper Dust"
 tin_dust = "Tin Dust"
 bronze_dust = "Bronze Dust"
 steel_dust = "Steel Dust"
 copper_ingot = "Copper Ingot"
 tin_ingot = "Tin Ingot"
 bronze_ingot = "Bronze Ingot"
 steel_ingot = "Steel Ingot"
 bronze_sword = "Bronze Sword"
 bronze_shovel = "Bronze Shovel"
 bronze_pickaxe = "Bronze Pickaxe"
 bronze_axe = "Bronze Axe"
 bronze_hoe = "Bronze Hoe"
 steel_sword = "Steel Sword"
 steel_shovel = "Steel Shovel"
 steel_pickaxe = "Steel Pickaxe"
 steel_axe = "Steel Axe"
 steel_hoe = "Steel Hoe"

[itemGroup.flux]
 items = "Flux Items"

[block.flux]
 fluxgen = "Flux Generator"
 grinding_mill = "Grinding Mill"
 alloy_caster = "Alloy Caster"
 washer = "Washer"
 compactor = "Compactor"
 copper_ore = "Copper Ore"
 tin_ore = "Tin Ore"
 copper_block = "Block of Copper"
 tin_block = "Block of Tin"
 bronze_block = "Block of Bronze"
 steel_block = "Block of Steel"
 energy_cable = "Energy Cable"
 digger = "Digger"
 farmer = "Farmer"
 butcher = "Butcher"
 mob_pounder = "Mob Pounder"
 item_absorber = "Item Absorber"
 multifactory = "Multifactory"
 rrtable = "Recipe Research Table"
 online_market = "Online Market"

[container.flux]
 fluxgen = "Flux Generator"
 grinding_mill = "Grinding Mill"
 alloy_caster = "Alloy Caster"
 washer = "Washer"
 compactor = "Compactor"

[gui.flux.recipebook.toggleRecipes]
 grindable = "Showing grindable only"
 alloyable = "Showing alloyable only"
 washable = "Showing washable only"
 compactable = "Showing compactable only"

[gui.flux.jei.category]
 grinding = "Grinding"
 alloying = "Alloying"
 washing = "Washing"
 compacting = "Compacting"

[entity.minecraft.villager.flux]
 flux_engineer = "Flux Engineer"
